apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: canary-check
spec:
  args:
  - name: namespace
  metrics:
  - count: 3
    failureLimit: 1
    interval: 10s
    name: canary-health
    provider:
      web:
        jsonPath: '{$.status}'
        url: http://kargo-demo-canary.{{args.namespace}}.svc.cluster.local:3000/health
    successCondition: result == 'healthy'
  - count: 3
    failureLimit: 1
    interval: 10s
    name: canary-products
    provider:
      web:
        jsonPath: '{$.count}'
        url: http://kargo-demo-canary.{{args.namespace}}.svc.cluster.local:3000/products
    successCondition: asInt(result) >= 1
