apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: canary-check
spec:
  args:
  - name: namespace
  metrics:
  - count: 3
    failureLimit: 1
    interval: 10s
    name: canary-memory-check
    provider:
      prometheus:
        address: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
        query: |
          max(
            sum(
              container_memory_working_set_bytes{
                namespace="kargo-demo-prod",
                pod=~"kargo-demo-rollout-.*",
                container!="",
                container!="POD"
              }
            ) by (pod)
          ) / 1024 / 1024
    successCondition: result[0] < 150
