apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: canary-check
spec:
  metrics:
  - count: 1
    failureLimit: 0
    name: canary-check
    provider:
      job:
        spec:
          backoffLimit: 1
          template:
            spec:
              containers:
              - command:
                - /bin/sh
                - -c
                - |
                  echo "Testing canary service..."
                  curl -sf http://kargo-demo-canary:3000/ || exit 1
                  echo "Canary check passed!"
                image: curlimages/curl:latest
                name: check
              restartPolicy: Never
