apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  labels:
    app: kargo-demo
  name: kargo-demo-rollout
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kargo-demo
  strategy:
    canary:
      abortScaleDownDelaySeconds: 30
      canaryService: kargo-demo-canary
      stableService: kargo-demo
      steps:
      - setWeight: 20
      - pause:
          duration: 30
      - analysis:
          templates:
          - templateName: canary-check
      - setWeight: 50
      - pause:
          duration: 30
      - setWeight: 100
  template:
    metadata:
      labels:
        app: kargo-demo
    spec:
      containers:
      - image: public.ecr.aws/nginx/nginx:1.29.1
        name: nginx
