apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  labels:
    app: kargo-demo
  name: kargo-demo-rollout
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kargo-demo
  strategy:
    canary:
      abortScaleDownDelaySeconds: 30
      canaryService: kargo-demo-canary
      stableService: kargo-demo
      steps:
      - setWeight: 20
      - pause:
          duration: 30
      - analysis:
          args:
          - name: namespace
            value: kargo-demo-staging
          templates:
          - templateName: canary-check
      - setWeight: 50
      - pause:
          duration: 30
      - setWeight: 100
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
      labels:
        app: kargo-demo
    spec:
      containers:
      - env:
        - name: PORT
          value: "8080"
        - name: REDIS_HOST
          value: localhost
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_PASSWORD
          value: demo
        - name: LOG_LEVEL
          value: info
        image: 964108025908.dkr.ecr.us-east-1.amazonaws.com/product-api:1.0.0
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 15
        name: product-api
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
      - env:
        - name: REDIS_PASSWORD
          value: demo
        - name: REDIS_DISABLE_COMMANDS
          value: ""
        - name: REDIS_AOF_ENABLED
          value: "no"
        image: bitnamilegacy/redis:7.4.3
        name: redis
        ports:
        - containerPort: 6379
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 32Mi
