apiVersion: kargo.akuity.io/v1alpha1
kind: PromotionTask
metadata:
  name: demo-promo-process
  namespace: kargo-demo
spec:
  vars:
  - name: gitopsRepo
    value: https://github.com/crmagz/argo-kargo-demo
  - name: imageRepo
    value: 964108025908.dkr.ecr.us-east-1.amazonaws.com/product-api
  steps:
  - uses: git-clone
    config:
      repoURL: ${{ vars.gitopsRepo }}
      checkout:
        - branch: main
          path: ./src
        - branch: stage/${{ ctx.stage }}
          create: true
          path: ./out
  - uses: git-clear
    config:
      path: ./out
  - uses: kustomize-set-image
    as: update-image
    config:
      path: ./src/base
      images:
        - image: ${{ vars.imageRepo }}
          tag: ${{ imageFrom(vars.imageRepo).Tag }}
  - uses: kustomize-build
    config:
      path: ./src/stages/${{ ctx.stage }}
      outPath: ./out
  - uses: git-commit
    as: commit
    config:
      path: ./out
      message: ${{ task.outputs['update-image'].commitMessage }}
  - uses: git-push
    config:
      path: ./out
  - uses: argocd-update
    config:
      apps:
        - name: kargo-demo-${{ ctx.stage }}
          sources:
            - repoURL: ${{ vars.gitopsRepo }}
              desiredRevision: ${{ task.outputs.commit.commit }}
