---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev
  namespace: kargo-demo
  annotations:
    kargo.akuity.io/color: green
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: kargo-demo
    sources:
      direct: true
  promotionTemplate:
    spec:
      steps:
      - task:
          name: demo-promo-process
        as: promo-process
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: staging
  namespace: kargo-demo
  annotations:
    kargo.akuity.io/color: yellow
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: kargo-demo
    sources:
      stages:
      - dev
  promotionTemplate:
    spec:
      steps:
      - task:
          name: demo-promo-process
        as: promo-process
  verification:
    analysisTemplates:
    - name: verify-staging
---
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: verify-staging
  namespace: kargo-demo
spec:
  metrics:
  - name: staging-health-check
    provider:
      web:
        url: http://kargo-demo.kargo-demo-staging.svc.cluster.local:3000/health
        jsonPath: "{$.status}"
    successCondition: "result == 'healthy'"
    interval: 10s
    count: 3
    failureLimit: 1
  - name: staging-products-check
    provider:
      web:
        url: http://kargo-demo.kargo-demo-staging.svc.cluster.local:3000/products
        jsonPath: "{$.count}"
    successCondition: "asInt(result) >= 1"
    interval: 10s
    count: 3
    failureLimit: 1
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod
  namespace: kargo-demo
  annotations:
    kargo.akuity.io/color: red
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: kargo-demo
    sources:
      stages:
      - staging
  promotionTemplate:
    spec:
      steps:
      - task:
          name: demo-promo-process
        as: promo-process
