---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev
  namespace: kargo-demo
  annotations:
    kargo.akuity.io/color: green
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: kargo-demo
    sources:
      direct: true
  promotionTemplate:
    spec:
      steps:
      - task:
          name: demo-promo-process
        as: promo-process
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: staging
  namespace: kargo-demo
  annotations:
    kargo.akuity.io/color: yellow
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: kargo-demo
    sources:
      stages:
      - dev
  promotionTemplate:
    spec:
      steps:
      - task:
          name: demo-promo-process
        as: promo-process
  verification:
    analysisTemplates:
    - name: verify-staging
---
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: verify-staging
  namespace: kargo-demo
spec:
  metrics:
  - name: verify-staging-memory
    provider:
      prometheus:
        address: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
        query: |
          max(
            sum(
              container_memory_working_set_bytes{
                namespace="kargo-demo-staging",
                pod=~"kargo-demo-rollout-.*",
                container!="",
                container!="POD"
              }
            ) by (pod)
          ) / 1024 / 1024
    successCondition: result[0] < 150
    interval: 10s
    count: 3
    failureLimit: 1
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod
  namespace: kargo-demo
  annotations:
    kargo.akuity.io/color: red
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: kargo-demo
    sources:
      stages:
      - staging
  promotionTemplate:
    spec:
      steps:
      - task:
          name: demo-promo-process
        as: promo-process
  verification:
    analysisTemplates:
    - name: verify-prod
---
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: verify-prod
  namespace: kargo-demo
spec:
  metrics:
  - name: verify-prod-memory
    provider:
      prometheus:
        address: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
        query: |
          max(
            sum(
              container_memory_working_set_bytes{
                namespace="kargo-demo-prod",
                pod=~"kargo-demo-rollout-.*",
                container!="",
                container!="POD"
              }
            ) by (pod)
          ) / 1024 / 1024
    successCondition: result[0] < 150
    interval: 10s
    count: 3
    failureLimit: 1
