apiVersion: batch/v1
kind: Job
metadata:
  name: integration-test
  namespace: kargo-demo-dev
spec:
  ttlSecondsAfterFinished: 60
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: curl-check
          image: curlimages/curl:latest
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Hello from the integration test job!"           
