apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: canary-check
spec:
  args:
  - name: namespace
  metrics:
  - name: canary-health
    provider:
      web:
        url: http://kargo-demo-canary.{{args.namespace}}.svc.cluster.local:3000/health
        jsonPath: "{$.status}"
    successCondition: "result == 'healthy'"
    interval: 10s
    count: 3
    failureLimit: 1
  - name: canary-products
    provider:
      web:
        url: http://kargo-demo-canary.{{args.namespace}}.svc.cluster.local:3000/products
        jsonPath: "{$.count}"
    successCondition: "asInt(result) >= 1"
    interval: 10s
    count: 3
    failureLimit: 1
