apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: canary-check
spec:
  metrics:
  - name: canary-check
    provider:
      job:
        spec:
          template:
            spec:
              containers:
              - name: check
                image: alpine:latest
                command: [sleep, "5"]
              restartPolicy: Never
          backoffLimit: 1
    # Run once and succeed
    count: 1
    failureLimit: 0
