apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: kargo-demo-rollout
  labels:
    app: kargo-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kargo-demo
  template:
    metadata:
      labels:
        app: kargo-demo
    spec:
      containers:
      - name: nginx
        image: public.ecr.aws/nginx/nginx:1.26.0
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: {duration: 30}
      - analysis:
          templates:
          - templateName: canary-check
      - setWeight: 50
      - pause: {duration: 30}
      - setWeight: 100
      # Rollback automatically if analysis fails
      abortScaleDownDelaySeconds: 30
