apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: canary-check
spec:
  metrics:
  - name: canary-check
    provider:
      job:
        spec:
          template:
            spec:
              containers:
              - name: check
                image: curlimages/curl:latest
                command:
                - /bin/sh
                - -c
                - |
                  echo "Testing canary service..."
                  curl -sf http://kargo-demo-canary:3000/ || exit 1
                  echo "Simulating production verification failure..."
                  exit 1
              restartPolicy: Never
          backoffLimit: 1
    count: 1
    failureLimit: 0
